name: dial_verse
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  contacts_service: ^0.6.3
  flutter:
    sdk: flutter
  fpdart: ^1.1.0
  get: ^4.6.6
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/dv_logo.png
    - assets/logo_back.png
    - assets/icons/

  fonts:
    - family: AudioWide
      fonts:
        - asset: fonts/Audiowide-Regular.ttf

    - family: Chango
      fonts:
        - asset: fonts/Chango-Regular.ttf

    - family: Caviar
      fonts:
        - asset: fonts/CaviarDreams.ttf
        - asset: fonts/Caviar_Dreams_Bold.ttf
          weight: 700
